# Generated by Django 4.2.6 on 2023-10-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratedmovies',
            name='movie',
        ),
        migrations.AddField(
            model_name='ratedmovies',
            name='movie_id',
            field=models.CharField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratedmovies',
            name='movie_title',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
